"""
fasten codes typegen — generate IDE / type-checker stubs from a yaml catalog.

Adopters who use ``fasten.codes.load("fleet.codes.yaml")`` at runtime can
also run this offline tool to produce dev-only type stubs giving them
autocomplete on code names. Stubs are dev-time artefacts (``.pyi`` / ``.d.ts``
/ ``.go``); no runtime impact, no SDK dep.

Usage:

    fasten codes typegen fleet.codes.yaml --lang python > fleet_codes.pyi
    fasten codes typegen fleet.codes.yaml --lang ts     > fleet_codes.d.ts
    fasten codes typegen fleet.codes.yaml --lang go     > fleet_codes_gen.go

The yaml schema matches what ``fasten.codes.load()`` accepts.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any


def _yaml_loader() -> Any:
    try:
        import yaml
    except ImportError as e:
        raise RuntimeError(
            "fasten codes typegen requires pyyaml; install with: pip install pyyaml"
        ) from e
    return yaml


def _read_catalog(path: Path) -> tuple[str, dict[str, dict]]:
    yaml = _yaml_loader()
    doc = yaml.safe_load(path.read_text()) or {}
    if not isinstance(doc, dict):
        raise SystemExit(f"{path}: top-level must be a mapping")
    domain = doc.get("domain") or ""
    if not domain or not isinstance(domain, str):
        raise SystemExit(f"{path}: top-level 'domain' is required (string)")
    codes = doc.get("codes") or {}
    if not isinstance(codes, dict):
        raise SystemExit(f"{path}: 'codes' must be a mapping")
    return domain, codes


def _gen_python(domain: str, codes: dict[str, dict], src: Path) -> str:
    """Generate a Python type stub (.pyi) declaring each code as a string Literal.

    Adopters do:
      from fleet_codes_pyi import FleetCode
      def emit_one(code: FleetCode): ...
    """
    sorted_codes = sorted(codes)
    literals = ", ".join(f'"{c}"' for c in sorted_codes)
    body_lines = [
        f"# Generated by `fasten codes typegen` from {src.name} — do not edit.",
        f"# Domain: {domain!r}. Codes: {len(sorted_codes)}.",
        "from typing import Literal",
        "",
        f"FleetCode = Literal[{literals}]" if domain == "fleet" else (
            f"{domain.title().replace('-', '_')}Code = Literal[{literals}]"
        ),
        "",
    ]
    # Also expose each code as a module-level constant for autocomplete.
    body_lines.append("# Module-level constants for autocomplete:")
    for c in sorted_codes:
        body_lines.append(f"{c}: str")
    body_lines.append("")
    return "\n".join(body_lines)


def _gen_typescript(domain: str, codes: dict[str, dict], src: Path) -> str:
    """Generate a TypeScript .d.ts declaring each code as a string-literal union."""
    sorted_codes = sorted(codes)
    union = " | ".join(f"'{c}'" for c in sorted_codes)
    type_name = (
        "".join(p.capitalize() for p in domain.replace("-", "_").split("_"))
        + "Code"
    )
    lines = [
        f"// Generated by `fasten codes typegen` from {src.name} — do not edit.",
        f"// Domain: '{domain}'. Codes: {len(sorted_codes)}.",
        "",
        f"export type {type_name} = {union};",
        "",
        f"export const {type_name.upper()}: readonly {type_name}[];",
        "",
    ]
    return "\n".join(lines)


def _gen_go(domain: str, codes: dict[str, dict], src: Path) -> str:
    """Generate Go const declarations for each code."""
    sorted_codes = sorted(codes)
    type_name = (
        "".join(p.capitalize() for p in domain.replace("-", "_").split("_"))
        + "Code"
    )
    pkg = domain.replace("-", "_")
    lines = [
        f"// Generated by `fasten codes typegen` from {src.name} — do not edit.",
        f"// Domain: {domain!r}. Codes: {len(sorted_codes)}.",
        "",
        f"package {pkg}",
        "",
        f"// {type_name} is a string-typed wrapper for {domain!r} audit codes.",
        f"type {type_name} string",
        "",
        "const (",
    ]
    for c in sorted_codes:
        lines.append(f'\t{c} {type_name} = "{c}"')
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def _gen_rust(domain: str, codes: dict[str, dict], src: Path) -> str:
    """Generate Rust const &str declarations for each code."""
    sorted_codes = sorted(codes)
    lines = [
        f"// Generated by `fasten codes typegen` from {src.name} — do not edit.",
        f"// Domain: {domain!r}. Codes: {len(sorted_codes)}.",
        "",
    ]
    for c in sorted_codes:
        lines.append(f'pub const {c}: &str = "{c}";')
    lines.append("")
    return "\n".join(lines)


_GENERATORS = {
    "python": _gen_python,
    "py": _gen_python,
    "ts": _gen_typescript,
    "typescript": _gen_typescript,
    "go": _gen_go,
    "rust": _gen_rust,
    "rs": _gen_rust,
}


def run(yaml_path: str, lang: str, out: str | None = None) -> int:
    src = Path(yaml_path)
    if not src.exists():
        print(f"fasten typegen: file not found: {yaml_path}", file=sys.stderr)
        return 2

    gen = _GENERATORS.get(lang.lower())
    if gen is None:
        valid = ", ".join(sorted(set(_GENERATORS)))
        print(f"fasten typegen: unknown --lang {lang!r}; valid: {valid}", file=sys.stderr)
        return 2

    domain, codes = _read_catalog(src)
    text = gen(domain, codes, src)

    if out is None or out == "-":
        sys.stdout.write(text)
    else:
        Path(out).write_text(text)
    return 0
