"""Tests for `fasten codes typegen` CLI (P1-11 typegen)."""
import textwrap
from pathlib import Path

import pytest


yaml = pytest.importorskip("yaml")


@pytest.fixture
def fleet_yaml(tmp_path: Path) -> Path:
    p = tmp_path / "fleet.codes.yaml"
    p.write_text(textwrap.dedent("""\
        domain: fleet
        codes:
          FLEET_NODE_REGISTERED:
            severity: info
            description: Edge node claimed
          FLEET_DEPLOY_FAILED:
            severity: error
            retention_class: long
            description: Deploy failed
    """))
    return p


def _run(yaml_path: Path, lang: str) -> str:
    from fasten.cli._typegen import run
    import io
    import sys
    buf = io.StringIO()
    saved = sys.stdout
    sys.stdout = buf
    try:
        rc = run(yaml_path=str(yaml_path), lang=lang, out=None)
    finally:
        sys.stdout = saved
    assert rc == 0
    return buf.getvalue()


def test_python_stub(fleet_yaml):
    out = _run(fleet_yaml, "python")
    assert "Generated by `fasten codes typegen`" in out
    assert "Domain: 'fleet'" in out
    # Sorted Literal type
    assert 'Literal["FLEET_DEPLOY_FAILED", "FLEET_NODE_REGISTERED"]' in out
    # Module-level constants
    assert "FLEET_NODE_REGISTERED: str" in out
    assert "FLEET_DEPLOY_FAILED: str" in out


def test_typescript_stub(fleet_yaml):
    out = _run(fleet_yaml, "ts")
    assert "Generated by `fasten codes typegen`" in out
    assert "export type FleetCode = 'FLEET_DEPLOY_FAILED' | 'FLEET_NODE_REGISTERED';" in out
    assert "export const FLEETCODE: readonly FleetCode[];" in out


def test_go_stub(fleet_yaml):
    out = _run(fleet_yaml, "go")
    assert "package fleet" in out
    assert "type FleetCode string" in out
    assert 'FLEET_NODE_REGISTERED FleetCode = "FLEET_NODE_REGISTERED"' in out


def test_rust_stub(fleet_yaml):
    out = _run(fleet_yaml, "rust")
    assert 'pub const FLEET_NODE_REGISTERED: &str = "FLEET_NODE_REGISTERED";' in out
    assert 'pub const FLEET_DEPLOY_FAILED: &str = "FLEET_DEPLOY_FAILED";' in out


def test_unknown_lang_raises(fleet_yaml):
    from fasten.cli._typegen import run
    rc = run(yaml_path=str(fleet_yaml), lang="cobol", out=None)
    assert rc == 2


def test_missing_file():
    from fasten.cli._typegen import run
    rc = run(yaml_path="/nonexistent.yaml", lang="python", out=None)
    assert rc == 2


def test_write_to_file(fleet_yaml, tmp_path):
    from fasten.cli._typegen import run
    out_file = tmp_path / "stub.pyi"
    rc = run(yaml_path=str(fleet_yaml), lang="python", out=str(out_file))
    assert rc == 0
    text = out_file.read_text()
    assert "FLEET_NODE_REGISTERED" in text
